trigger:
  branches:
    include:
      - main
      - development

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: dotnet build --configuration Release
  displayName: 'dotnet build'

- script: dotnet test --configuration Release --no-build
  displayName: 'dotnet test'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifact: 'test-results'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: '<Azure Subscription>'
    appType: 'webApp'
    WebAppName: '<Your Web App Name>'
    packageForLinux: '$(Pipeline.Workspace)/**/*.zip'
    enableCustomDeployment: true
    deploymentType: 'zipDeploy'
